# Generated by Django 5.2.5 on 2025-09-24 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranteadmin',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_restaurante', to=settings.AUTH_USER_MODEL),
        ),
    ]
