# Generated by Django 5.2.5 on 2025-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
