# Generated by Django 5.2.5 on 2025-09-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username_personalizado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
