# Generated by Django 5.2.5 on 2025-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_last_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
