# Generated by Django 5.2.5 on 2025-09-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_restauranteadmin_usuario'),
        ('usuarios', '0003_usuario_avatar_color'),
    ]

    operations = [
    ]
