# Generated by Django 5.2.5 on 2025-09-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username_personalizado',
        ),
    ]
