# Generated by Django 5.2.5 on 2025-09-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_20250924_1749'),
        ('usuarios', '0004_merge_20250924_1801'),
    ]

    operations = [
    ]
