# Generated by Django 5.2.5 on 2025-09-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='creada_en',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='Cliente', max_length=100),
        ),
    ]
