# Generated by Django 5.2.5 on 2025-09-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_creada_en_reserva_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa'),
        ),
    ]
