# Generated by Django 5.2.5 on 2025-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='fecha_fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
