# Generated by Django 5.2.5 on 2025-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='duracion_horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_horas', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
