# Generated by Django 5.2.5 on 2025-09-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_restauranteadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restauranteadmin',
        ),
    ]
